# Generated by Django 3.2 on 2021-04-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da venda')),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('data_hora_venda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
