# Generated by Django 3.2 on 2021-04-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210426_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('cnpj', models.CharField(max_length=11, verbose_name='CNPJ')),
                ('email_fornecedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
    ]
