# Generated by Django 3.2 on 2021-04-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210426_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionário',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=255, verbose_name='Matricula')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
    ]
